// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: URPacketType.proto

#import "GPBProtocolBuffers.h"

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class Result;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum URPacketType

typedef GPB_ENUM(URPacketType) {
  /// Value used if any message's field encounters a value that is not defined
  /// by this enum. The message will also have C functions to get/set the rawValue
  /// of the field.
  URPacketType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  ///无效uri
  URPacketType_KUriInvalid = 0,
  URPacketType_KUriPloginReq = 10,
  URPacketType_KUriPloginRes = 11,
  URPacketType_KUriPlogoutReq = 12,
  URPacketType_KUriPlogoutRes = 13,
};

GPBEnumDescriptor *URPacketType_EnumDescriptor(void);

/// Checks to see if the given value is defined by the enum or was not known at
/// the time this source was generated.
BOOL URPacketType_IsValidValue(int32_t value);

#pragma mark - Enum ResultType

typedef GPB_ENUM(ResultType) {
  /// Value used if any message's field encounters a value that is not defined
  /// by this enum. The message will also have C functions to get/set the rawValue
  /// of the field.
  ResultType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  ResultType_ResultTypeOk = 0,
  ResultType_ResultTypeFail = 1,
};

GPBEnumDescriptor *ResultType_EnumDescriptor(void);

/// Checks to see if the given value is defined by the enum or was not known at
/// the time this source was generated.
BOOL ResultType_IsValidValue(int32_t value);

#pragma mark - UrpacketTypeRoot

/// Exposes the extension registry for this file.
///
/// The base class provides:
/// @code
///   + (GPBExtensionRegistry *)extensionRegistry;
/// @endcode
/// which is a @c GPBExtensionRegistry that includes all the extensions defined by
/// this file and all files that it depends on.
@interface UrpacketTypeRoot : GPBRootObject
@end

#pragma mark - PHeader

typedef GPB_ENUM(PHeader_FieldNumber) {
  PHeader_FieldNumber_Uid = 1,
  PHeader_FieldNumber_Seqid = 2,
  PHeader_FieldNumber_Platform = 3,
  PHeader_FieldNumber_Version = 4,
  PHeader_FieldNumber_Result = 5,
};

@interface PHeader : GPBMessage

@property(nonatomic, readwrite) uint64_t uid;

@property(nonatomic, readwrite) uint64_t seqid;

@property(nonatomic, readwrite) uint32_t platform;

@property(nonatomic, readwrite) uint32_t version;

@property(nonatomic, readwrite, strong, null_resettable) Result *result;
/// Test to see if @c result has been set.
@property(nonatomic, readwrite) BOOL hasResult;

@end

#pragma mark - Result

typedef GPB_ENUM(Result_FieldNumber) {
  Result_FieldNumber_Code = 1,
  Result_FieldNumber_ResMsg = 2,
};

@interface Result : GPBMessage

@property(nonatomic, readwrite) ResultType code;

@property(nonatomic, readwrite, copy, null_resettable) NSString *resMsg;

@end

/// Fetches the raw value of a @c Result's @c code property, even
/// if the value was not defined by the enum at the time the code was generated.
int32_t Result_Code_RawValue(Result *message);
/// Sets the raw value of an @c Result's @c code property, allowing
/// it to be set to a value that was not defined by the enum at the time the code
/// was generated.
void SetResult_Code_RawValue(Result *message, int32_t value);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
