// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: URProtocol.proto

#import "GPBProtocolBuffers.h"

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class PHeader;
@class URLoginReq;
@class URLoginRes;
@class URLogoutReq;
@class URLogoutRes;
GPB_ENUM_FWD_DECLARE(URPacketType);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - UrprotocolRoot

/// Exposes the extension registry for this file.
///
/// The base class provides:
/// @code
///   + (GPBExtensionRegistry *)extensionRegistry;
/// @endcode
/// which is a @c GPBExtensionRegistry that includes all the extensions defined by
/// this file and all files that it depends on.
@interface UrprotocolRoot : GPBRootObject
@end

#pragma mark - URProtocol

typedef GPB_ENUM(URProtocol_FieldNumber) {
  URProtocol_FieldNumber_Uri = 1,
  URProtocol_FieldNumber_Header = 2,
  URProtocol_FieldNumber_LoginReq = 3,
  URProtocol_FieldNumber_LoginRes = 4,
  URProtocol_FieldNumber_LogoutReq = 5,
  URProtocol_FieldNumber_LogoutRes = 6,
};

@interface URProtocol : GPBMessage

@property(nonatomic, readwrite) enum URPacketType uri;

@property(nonatomic, readwrite, strong, null_resettable) PHeader *header;
/// Test to see if @c header has been set.
@property(nonatomic, readwrite) BOOL hasHeader;

@property(nonatomic, readwrite, strong, null_resettable) URLoginReq *loginReq;
/// Test to see if @c loginReq has been set.
@property(nonatomic, readwrite) BOOL hasLoginReq;

@property(nonatomic, readwrite, strong, null_resettable) URLoginRes *loginRes;
/// Test to see if @c loginRes has been set.
@property(nonatomic, readwrite) BOOL hasLoginRes;

@property(nonatomic, readwrite, strong, null_resettable) URLogoutReq *logoutReq;
/// Test to see if @c logoutReq has been set.
@property(nonatomic, readwrite) BOOL hasLogoutReq;

@property(nonatomic, readwrite, strong, null_resettable) URLogoutRes *logoutRes;
/// Test to see if @c logoutRes has been set.
@property(nonatomic, readwrite) BOOL hasLogoutRes;

@end

/// Fetches the raw value of a @c URProtocol's @c uri property, even
/// if the value was not defined by the enum at the time the code was generated.
int32_t URProtocol_Uri_RawValue(URProtocol *message);
/// Sets the raw value of an @c URProtocol's @c uri property, allowing
/// it to be set to a value that was not defined by the enum at the time the code
/// was generated.
void SetURProtocol_Uri_RawValue(URProtocol *message, int32_t value);

#pragma mark - URLoginReq

typedef GPB_ENUM(URLoginReq_FieldNumber) {
  URLoginReq_FieldNumber_Passport = 1,
  URLoginReq_FieldNumber_Password = 2,
};

@interface URLoginReq : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *passport;

@property(nonatomic, readwrite, copy, null_resettable) NSString *password;

@end

#pragma mark - URLoginRes

@interface URLoginRes : GPBMessage

@end

#pragma mark - URLogoutReq

typedef GPB_ENUM(URLogoutReq_FieldNumber) {
  URLogoutReq_FieldNumber_Passport = 1,
  URLogoutReq_FieldNumber_Password = 2,
};

@interface URLogoutReq : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *passport;

@property(nonatomic, readwrite, copy, null_resettable) NSString *password;

@end

#pragma mark - URLogoutRes

@interface URLogoutRes : GPBMessage

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
